### ISSUE TITLE
node-sass 是不是坏了。。。

### ISSUE THREAD

**Issue by Ppsj** [tomi-li/vue2-admin-template#1]
![d vkx5 fez 7m_q6o39mvf](https://cloud.githubusercontent.com/assets/18297094/24129877/5f03e596-0e20-11e7-8785-bd0e19e659c2.png)

**Comment by tomi-li** [comment]
额。。 没想到竟然有人在用。。 还在提 issue。
哈哈哈
没有啦  node-sass  是一个 package json 里面的 依赖
重新装一下就好了。 npm install 下。
或者试试 yarn ~ 

我刚刚试着重新 clone install 了下  没有发现问题

**Comment by Ppsj** [comment]
好吧。我是我这边网络出问题了，VPN挂了。谢谢。作者的回答
